#!/usr/bin/env bash

set -euo pipefail

cd $(git rev-parse --show-toplevel)

bundle install --jobs 4 --retry 3

gem build logstash-output-prometheus.gemspec

if [[ -z "${CI_GEM_NAME-}" ]]; then
	echo "Successfully built! Install in your logstash by running..."
	echo "logstash-plugin install $PWD/logstash-output-prometheus-0.1.3.gem from your logstash directory"
else
	echo "Successfully built!"
	# Makes the assumption that there is only one build.
	mv logstash-output-prometheus*.gem "${CI_GEM_NAME}"
fi